// Generated by dia2code
#ifndef AI__AI__H
#define AI__AI__H

#include <string>
#include <vector>

namespace state {
  class Game;
}

#include "state/Game.hpp"

namespace ai {

  /// class AI - 
  class AI {
    // Attributes
  public:
    std::string color;
  protected:
    state::Game* ai;
    bool player_a;
    // Operations
  public:
    AI (state::Game& game, std::string color);
    virtual std::vector<int> runAI ();
    // Setters and Getters
    const state::Game*& getAi() const;
    void setAi(const state::Game*& ai);
    bool getPlayer_a() const;
    void setPlayer_a(bool player_a);
  };

};

#endif
