// Generated by dia2code
#ifndef AI__HEURISTICAI__H
#define AI__HEURISTICAI__H

#include <string>
#include <vector>

namespace state {
  class Game;
};
namespace ai {
  class AI;
}

#include "AI.hpp"

namespace ai {

  /// class HeuristicAI - 
  class HeuristicAI : public ai::AI {
    // Operations
  public:
    HeuristicAI (state::Game& game, std::string color);
    std::vector<int> runAI ();
    int BeeNeighbour ();
    std::vector<state::Insect> GetInsectsToMove ();
    // Setters and Getters
  };

};

#endif
